language: python
sudo: false
dist: xenial

python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev

env:
  - PYTHONUNBUFFERED="1"

before_install:
  - pip install --isolated --no-input --compile --exists-action=a --disable-pip-version-check --no-cache-dir --upgrade pip wheel setuptools
  - pip install --isolated --no-input --compile --exists-action=a --disable-pip-version-check --no-cache-dir --upgrade cookiecutter

script:
  - cookiecutter . --no-input
  - cd project_slug
  - pip install  --isolated --no-input --compile --exists-action=i --disable-pip-version-check --no-cache-dir -r requirements/local.txt

notifications:
  email:
    on_success: never
    on_failure: never
