language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"

before_install:
  - pip install mock
  - pip install cookiecutter

script:
  - cookiecutter . --no-input
  - cd project_name
  - pip install --no-input --exists-action=i -r requirements/local.txt --use-wheel

notifications:
  email:
    on_success: never
    on_failure: never
