language: python
sudo: false
python:
  - 3.5
  
before_install:
  - pip install --quiet --upgrade cookiecutter

script:
  - cookiecutter . --no-input
  - cd project_slug
  - pip install --no-input --exists-action=i -r requirements/local.txt --use-wheel

notifications:
  email:
    on_success: never
    on_failure: never
