language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
  - "nightly"

before_install:
  - pip install mock
  - pip install cookiecutter

script:
  - cookiecutter . --no-input

notifications:
  email:
    on_success: never
    on_failure: never
